language: php

sudo: false

php:
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - mkdir -p build/tests/
  - vendor/bin/phpunit --coverage-text --coverage-clover=build/tests/coverage.xml

notifications:
  email:
    on_success: never
    on_failure: always